### ISSUE TITLE
Minor documentation correction

### ISSUE THREAD

**Issue by liamh** [sisl/SatelliteDynamics.jl#17]
https://github.com/sisl/SatelliteDynamics.jl/blob/e51002c71e6097e390e89259c8525635c9a9ecf8/src/simulation/propagators.jl#L15

Looks like this duplicated the line two lines prior, should say something like "sun-facing area affected by solar radiation pressure".

**Comment by duncaneddy** [comment]
Ah yes, good catch. I'll fix it in the next release. Thank you!

**Comment by duncaneddy** [comment]
This was fixed in [this](https://github.com/sisl/SatelliteDynamics.jl/commit/10895359b5df1a3360e7ba8cd3f08aa0b5c5ebe6) commit on the deb brach.

Closing the issue and thank you for reporting it!
